language: ruby

rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - jruby-1.7.19
  - ruby-head
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

script: bundle exec rspec spec/htmless_spec.rb
